[dev]
    framework = "#custom"
    command = "yarn dev"
    autoLaunch = false
    targetPort = 3000

[build]
    command = "yarn build"
    publish = "dist"

[[plugins]]
    package = "netlify-plugin-minify-html"
    [plugins.inputs.minifierOptions]
        collapseWhitespace = true

[[redirects]]
    from = "https://elastic-varahamihira-cb3fa7.netlify.app/"
    to = "https://sngr.dev/"
    status = 301
    force = true
