[dev]
    command = "yarn dev"
    autoLaunch = false

[build]
    command = "yarn build"
    publish = "dist"

[[plugins]]
    package = "netlify-plugin-minify-html"
    [plugins.inputs.minifierOptions]
        collapseWhitespace = true
        minifyJS = true
        processScripts = ["module"]

[[redirects]]
    from = "https://elastic-varahamihira-cb3fa7.netlify.app/*"
    to = "https://sngr.dev/:splat"
    status = 301
    force = true
