[dev]
    framework = "#custom"
    command = "npx pnpm start"
    autoLaunch = false
    targetPort = 3000

[build.environment]
    NODE_VERSION = "14.17.1"
    NPM_FLAGS = "--prefix=/dev/null"

[build]
    command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
    publish = "dist"

[[redirects]]
    from = "https://sastronegoro-dev.netlify.app/"
    to = "https://sngr.dev/"
    status = 301
    force = true